# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\"1\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\'\n\x0c\x45xistRequest\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status*:\n\x06Status\x12\r\n\tNOT_EXIST\x10\x00\x12\t\n\x05\x45XIST\x10\x01\x12\x16\n\x12INCORRECT_PASSWORD\x10\x02\x32\x31\n\x05Users\x12(\n\tUserExist\x12\x0c.UserRequest\x1a\r.ExistRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=107
  _globals['_STATUS']._serialized_end=165
  _globals['_USERREQUEST']._serialized_start=15
  _globals['_USERREQUEST']._serialized_end=64
  _globals['_EXISTREQUEST']._serialized_start=66
  _globals['_EXISTREQUEST']._serialized_end=105
  _globals['_USERS']._serialized_start=167
  _globals['_USERS']._serialized_end=216
# @@protoc_insertion_point(module_scope)
