# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cinema_library.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63inema_library.proto\"5\n\x15RecommendationRequest\x12\x1c\n\x08\x63\x61tegory\x18\x01 \x01(\x0e\x32\n.FilmGenre\"q\n\x04\x46ilm\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x19\n\x11small_description\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x1e\n\ncategoryes\x18\x05 \x03(\x0e\x32\n.FilmGenre\"\x14\n\x06\x46ilmId\x12\n\n\x02id\x18\x01 \x01(\x05\"8\n\x16RecommendationResponse\x12\x1e\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x05.Film*d\n\tFilmGenre\x12\x07\n\x03\x41LL\x10\x00\x12\n\n\x06\x43OMEDY\x10\x01\x12\r\n\tDETECTIVE\x10\x02\x12\x0c\n\x08THRILLER\x10\x03\x12\r\n\tFANTASTIC\x10\x04\x12\x0b\n\x07HORRORS\x10\x05\x12\t\n\x05\x44RAMA\x10\x06\x32j\n\x0fRecommendations\x12<\n\tRecommend\x12\x16.RecommendationRequest\x1a\x17.RecommendationResponse\x12\x19\n\x07GetFilm\x12\x07.FilmId\x1a\x05.Filmb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cinema_library_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILMGENRE']._serialized_start=274
  _globals['_FILMGENRE']._serialized_end=374
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=24
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=77
  _globals['_FILM']._serialized_start=79
  _globals['_FILM']._serialized_end=192
  _globals['_FILMID']._serialized_start=194
  _globals['_FILMID']._serialized_end=214
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=216
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=272
  _globals['_RECOMMENDATIONS']._serialized_start=376
  _globals['_RECOMMENDATIONS']._serialized_end=482
# @@protoc_insertion_point(module_scope)
